### ISSUE TITLE
What is the replacement for this tutorial?

### ISSUE THREAD

**Issue by kmthinkingrock** [spring-guides/deprecate-tut-rest#13]
I relied on this tutorial not only for the rest elements but also for some of the modeling inspiration - is there an updated tutorial that incorporates similar architecture and modeling?

The updated tutorials that I have found are quite different than this one, and I think it would be helpful to have this tutorial as an updated tutorial, or to know why it is deprecated.

Thanks

**Comment by gregturn** [comment]
This tutorial was deprecated for a handful of reasons.

1. The tools were antiquated and hard to maintain. We had markdown + two different post processors to generate the HTML output.
1. The tutorial wasn't so much focused on REST at it was on hexagonal architecture. The concepts of REST can be applied to many architectures. We decided that it was a stronger opinion on application architecture than we wished to put forth.
1. The verbosity of the code base frankly made it difficult to maintain.

Trying to patch it up was intractable. In lieu of that, @joshlong wrote a new tutorial, more tilted towards REST and less about architecture => https://spring.io/guides/tutorials/bookmarks/
